### ISSUE TITLE
Crossover only results in one offspring

### ISSUE THREAD

**Issue by wulfihm** [trevorstephens/gplearn#123]
Usually crossover produces two individuals by symmetrically replacing the subtrees in each other.
The crossover operator in gplearn however only produces one offspring, is there a reason it was implemented that way?

The ramification of this implementation is that genetic material from the parent is completely eradicated from the gene pool, because it is simply overwritten from genetic material from the donor.
When implemented in a symmetric fashion the genetic material is swapped and both are kept in the gene pool which may result in better results.

It would be relatively simple to do it.
The first one to return is as it is in the code: 
https://github.com/trevorstephens/gplearn/blob/07b41a150dbf7e16645268b88405514b7f23590a/gplearn/_program.py#L549-L551

The second individual would be:
```
        (donor[:donor_start +
                self.program[start:end] +
                donor[donor_end:])
```

Then a few adjustments in the function _parallel_evolve in genetic.py (because instead of adding one we add two)

Evolutionary speaking it may be even better that we only add one from the crossover or perhaps in the end it doesn't even make a huge difference if we do the operation twice to add two or do it once to add two.  

Opinions?

**Comment by pricebenjamin** [comment]
I think this sounds like a great idea. Perhaps make it optional by passing a keyword such as `symmetric_crossover=True` to the regressor? If you had time to implement this, I could try and look it over.

**Comment by wulfihm** [comment]
I already had it implemented. After a few tests it did not result in better programs or other noteworthy effects (at least as I was able to notice) so I scrapped it again. The extra hassle of dynamically dealing with more than one program being added didn't seem to be worth it.

**Comment by trevorstephens** [comment]
Thanks again for your research @wulfihm ... The original algorithm was largely guided by the field guide to GP. https://cswww.essex.ac.uk/staff/rpoli/gp-field-guide/24RecombinationandMutation.html#7_4 mentions that symmetric crossover is possible but rarely used. Can't really justify why they state that is the case, but in implementing the package it was a lot easier to only produce one offspring, especially when considering parallel options. So yeah, it was intentional. Is it ideal? Not really sure, but the complexity of pre-calculating what operations will occur and segmenting parallel streams on that seems like a lot of overhead. Due to the structure of the package with parallelisation etc, this one is in the too hard basket, helpful to know that you weren't able to get better results in your version too. Cheers.
