### ISSUE TITLE
Relax the value type check in gplearn.genetic.fit

### ISSUE THREAD

**Issue by onshek** [trevorstephens/gplearn#183]
`check_X_y` in `gplearn.genetic.fit` results in that y cannot contain `np.nan`:

```
    if multi_output:
        y = check_array(y, 'csr', force_all_finite=True, ensure_2d=False,
                        dtype=None)
    else:
        y = column_or_1d(y, warn=True)
        _assert_all_finite(y)
```

Why not use something like `pd.DataFrame(X).index.intersection(pd.Series(y).index)` to get the intersection of `X` and `y`, which can increase the robustness of the code and bring convenience to users (such as me) to customize functions.

**Comment by trevorstephens** [comment]
I'm sorry but I do not follow at all. Since `X` and `y` are numpy arrays, casting them to pandas will just give them a range index, and since they have to be the same number of samples, this code just gives you a range of integers up to your number of samples. What would that be used for?

**Comment by onshek** [comment]
The example above is not quite appropriate. What I want to say is only to emphasize the action of "taking intersection" instead of using `Pandas`.
The current code will check whether `X` and `y` contain missing values (`np.nan`). As long as they contain any missing value, an error will be raised. However, I think that we can actually intercept the intersection of `X` and `y` for training, which makes the code more user friendly. 
As an example:
```
X = np.array([[1, 2], [3, 4], [5, 4], [3, np.nan]])
y = np.array([1, np.nan, 4, 6])
```
We can still use the rest of the intersection:
```
tmp = np.concatenate((X, y.reshape(-1, 1)), axis=1)
#array([[ 1.,  2.,  1.],
#       [ 3.,  4., nan],
#       [ 5.,  4.,  4.],
#       [ 3., nan,  6.]])
com = tmp[~np.isnan(tmp).any(axis=1)]
#array([[1., 2., 1.],
#       [5., 4., 4.]])
```

**Comment by trevorstephens** [comment]
I see what you mean now. Essentially you are saying that we should drop samples with missing values silently.

This is something the user can easily do themselves as part of their data cleaning steps if they want to. It is also only one method of dealing with missing values, there are many imputation methods out there. In fact scikit-learn has a whole module dedicated to this: https://scikit-learn.org/stable/modules/impute.html

Another issue is that if there's missing data in the test X, what do we do when it comes time to make predictions with a train X that is likely also full of missing values? The predictions will be full of unexpected NANs because the user never cleaned up their data.

Thanks for the idea, but I'm not in favour of this change as it is a simple step that a user could do consciously, or choose another method of dealing with missing values. The existing error lets them know that their data is dirty, and they can choose how to go about fixing that.
