### ISSUE TITLE
Add function and params to control maximum of RAM can be used

### ISSUE THREAD

**Issue by ghost** [trevorstephens/gplearn#187]
Please, **for the big problems**: **RAM is overflow** and I think you can be implement an function for **limited and stop if RAM param is over limit**. 

Because on Linux, that can be crash all the operating system.

Thanks.

**Comment by wulfihm** [comment]
Saving all the history can overflow your ram. One solution can be to set the gplearn parameter `low_memory=True`.
```
        When set to ``True``, only the current generation is retained. Parent
        information is discarded. For very large populations or runs with many
        generations, this can result in substantial memory use reduction.
```
Otherwise you can also do it yourself:
https://stackoverflow.com/questions/41105733/limit-ram-usage-to-python-program

Another solution can be to slowly go larger with your problems and see if anything crashes.
