### ISSUE TITLE
A few suggestions on user-defined function

### ISSUE THREAD

**Issue by nnnet** [trevorstephens/gplearn#22]
Thank you for an interesting package

Do you have any plans to add the following options:
- In a user-defined function in addition to the data may be consist some parameters, for example, MovingAvg (a, 9)  -  9 is parameter. And each parameter may variate in the range, example [2,...., 25]
- Function can return a matrix - multiple columns
- Function can include a model, and we are interested in not only the results of the model, but model parameters, such as linear regression coefficients. On full train-set the coefficients is const, but on iteration lags the parameters will change.

If you plan to do, how soon we can expect the implementation ?

**Comment by trevorstephens** [comment]
Hi @nnnet , thanks for the feedback! :+1: Unfortunately most of your requests fall outside of the scope of this project. Basically, the `gplearn` project goals is to offer a fairly streamlined interface into GP with a scikit-learn style API. Adding a large amount of complexity to what can be achieved for more specific needs means leaving that behind and moving towards a fully customizable architecture. There are other packages out there that fill that need at the cost of more set-up time by the user.

I don't have any immediate plans for adding a "parameter" type of node for the next release, though that might be something that I consider in a future release down the road. One obvious complication would be that you would need to constrain certain inputs to each function which adds a good amount of complexity to creating user-defined functions. Anyhow, I'll tag this feature request and leave it open for any other feedback from other users.

Your example of a moving average function does not really fit within the existing framework. There is no concept of "time" in the input datasets, so that would be tricky to implement without the user-defined function pointing to an external column of timestamps (outside of X). That should be workable within the existing function definition framework though (without the evolving parameters part) although subsampling throws a spanner in the works.

At this stage I do not plan on adding support for returning multiple columns from a function. That deviates too much from the tree-based structure of the base programs and would make the recursion of tree more expensive potentially.

You may be able to implement such a model-based function within the master branch function framework. Again, no immediate plans for parameter nodes. But I may revisit this after the next release if there is sufficient demand.

Thanks again for your feedback, I hope you understand the goals of the project do not align well with many of these specific requests.

**Comment by nnnet** [comment]
@trevorstephens , thanks for the quick response.
Of course I understand your objectives and respect them.
Tell you a secret :) I have realized these and other features, but your code is written very nice and some hacks were useful for me - thanks again for the package and waiting new release.
