### ISSUE TITLE
What's the best practice to add bound limit to a chromosome?

### ISSUE THREAD

**Issue by AnakinCN** [trevorstephens/gplearn#224]
I wonder what's the best way to add a top level nodes that can do something like:

if ((lowerNodeValue) > upperLimit) return upperLimit;
if ((lowerNodeValue) < lowerLimit) return lowerLimit;

Thanks a lot.

**Comment by AnakinCN** [comment]
>

**Comment by trevorstephens** [comment]
What do you mean by a top level node? As in the final node so that the output is cropped every time for every program?

If so, that's not supported, you could add a custom function to do that and then make the fitness measure heavily penalise anything outside the range to get approximately close to that behaviour potentially.

**Comment by trevorstephens** [comment]
You could also hack the source code of course and add a transformer similar to how it's implemented in the classifier

**Comment by AnakinCN** [comment]
Thank you
