### ISSUE TITLE
Solving an optimisation problem

### ISSUE THREAD

**Issue by jack-powers** [trevorstephens/gplearn#229]
Hi Trevor,

I just had a question on using gplearn to solve an optimisation problem. I understand that you have constrained gplearn to solve symbolic regression problems, however, I was wondering if it would be easy enough for myself just to remove this fitting functionality and just evolve a program to maximise an objective function?

I plan to define a custom fitness function that runs a simulation. The input of the simulation will be the functional form of an individual (with a fixed number of features) and the output will be two values (performance metrics of the simulation). The fitness value is then the weighted sum of these two output values. 

The goal is to evolve the functional form to maximise its fitness, and hence achieve a form that maximises performance in the simulation. As such, there would not be such a need for the regression vectors. In your opinion would gplearn be suited to serve as the foundations for such a project? 

Thank you

Kind regards,
Jack

**Comment by trevorstephens** [comment]
Hi there @jack-powers , it sounds as if you should seek a more flexible package, perhaps DEAP might work for you? I have not personally used it but I understand it to be a more flexible engine for genetic algorithm problems. You are correct that I have limited gplearn to act more like a machine learning estimator that a "platform". The whole back-end of gplearn is built around numpy vectors of a training dataset so without knowing more about your problem, I would assume it is not readily "hacked" to fit your requirements.

**Comment by tudorelu** [comment]
I have implemented something similar with gplearn and it worked well for my needs. You can use a custom fitness function with the aim of maximising your desired metric - the only downside is that from within the fitness function you don't have access to the _individual_, rather only to its output (`y_pred`).

Your fitness function needs to take 3 parameters - `y`, `y_pred` and `w`. `y` is the target (normally, what you are optimising towards), `y_pred` is the prediction of an _individual_ solution, and `w` is something I don't completely understand, but it does not matter. Since you don't care to be as close as possible to `y`, but rather you want the `y_pred`  - which is the output of an _individual_ - to maximize some metric (IE weighted sum of two variables), in your fitness function you can ignore both `y` and `w` all together and only use `y_pred` to calculate your variables - that is, if you can devise a way to calculate the variables based solely on `y_pred`, without the access to the underlying _individual_.  

Assuming you can do that, here's a rough implementation:

```py

# define your function
def custom_fitness(y, y_pred, w):
        # use `y_pred` to make your calculations,
        # you can ignore `y` and `w`
        return weighted_sum(value_1, value_2)
 
# use the inbuilt make_fitness function to wrap it
fitn = make_fitness(custom_fitness, greater_is_better=True)

# pass the wrapped function to the regressor
est_gp = SymbolicRegressor(
        metric = fitn,
        # ... extra parameters here ...
        )
# train it
est_gp.fit(X_train, y_train)

```

Check out the custom fitness function section of the docs for more info.
