### ISSUE TITLE
Hall of fame (or elite) for SymbolicRegressor?

### ISSUE THREAD

**Issue by joosbuijsNL** [trevorstephens/gplearn#230]
Hi all,

First of all thanks for providing this excellent package, it will hopefully bring our data science project to the next level!

I do have a question though. When running a variation of the provided example for the SymbolicRegressor I noticed that the fitness of the best individual was not strictly increasing, but sometimes also decreasing. I experimented a bit and noticed that the hall_of_fame (which I assume is the list of elite programs that should not be modified) is empty after completion. Is an elite set of programs maintained which will survive the generations unmodified (but will create offspring etc.)?

Sub question: Or could the decrease of the best fitness be caused by setting max_samples < 1?

**Comment by trevorstephens** [comment]
Hey there @joosbuijsNL ... The hall of fame is only a thing for the SymbolicTransformer, where the point is to generate a matrix of hopefully independent vectors for another estimator to consume, whereas the Regressor is meant to find one good relationship. If you really want to look into a hall of fame for the regressor, you can inspect all of the last generation's programs through the `_programs` attribute and create one yourself, though it isn't designed to be user friendly. :grimacing: .. but it has no meaning outside the transformer and isn't used.

Hard to answer why the fitness is not strictly increasing for any given problem, nor do I particularly have the time to do so, but there's two parts for selection, the raw fitness and the parsimony penalty to it. It's possible that the best solutions are bigger than your parsimony allows, so selection favours less viable but smaller programs... Maybe try reducing it to see if that gets a better outcome. Then again, maybe it's the correct outcome because your "best" solution is overfit to the training set. Every problem is different and needs tuning.

**Comment by joosbuijsNL** [comment]
Hi @trevorstephens, thank you sooo much for your super fast reply (within 15 min.). Much appreciated!

I have some experience with GP and Python so I guess I can figure it out. Thanks for the hints.
