### ISSUE TITLE
convert variables names to original

### ISSUE THREAD

**Issue by jermaine1ronquillo** [trevorstephens/gplearn#73]
Is it possible to convert the variables in the equation to its original name (instead of X1, X2...), and add mapping function to shorten variable names in case the names are too long? Can we use sympy to convert the equation? Thank you

**Comment by trevorstephens** [comment]
Where would you want to see this representation? The `print` function, or the program tree plot, or both? The `print` function could be problematic due to the feature names being related to the data and hence should only be passed to `fit` if conforming to the `scikit-learn` standard API. The graphviz plot might be more of an option as this is its own method and happens after fitting.

As for `sympy` I don't particularly want to go down that road as many of the built-in functions rely on [closure](http://gplearn.readthedocs.org/en/latest/intro.html#closure) which means there are a lot of rounding checks that don't fit neatly into the `sympy` world and user-defined functions add a whole other level of complexity to that. Happy to hear further thoughts on this or a PR but it is not something that I am prioritising right now.

**Comment by jermaine1ronquillo** [comment]
Thank you for the response, the graphviz plot will do.
