### ISSUE TITLE
Questions about terminal or function selection conditions

### ISSUE THREAD

**Issue by ceylanb** [trevorstephens/gplearn#76]
In _program.py file, you used if condition below. I can't understand, why did you add `n_features` to `len(function_set)` ? And one another question is about `choice <= len(self.function_set))`, why? 

```
depth = len(terminal_stack)
choice = self.n_features + len(self.function_set)
choice = random_state.randint(choice)
# Determine if we are adding a function or terminal
if (depth < max_depth) and (method == 'full' or choice <= len(self.function_set)):
```

Last question; why did you use `terminal == self.n_features:` condition to select a terminal?
```
terminal = random_state.randint(self.n_features + 1)
if terminal == self.n_features:
    terminal = random_state.uniform(*self.const_range)
program.append(terminal)
```

**Comment by trevorstephens** [comment]
1 - At each new split in the tree we need either a new function, feature or constant to continue the growth of the program.
2 - Not sure on your question here. But assuming the question is why it is less than or equal to, that is where the tree needs a terminal node, so a variable or constant is required. If the choice is less than that then we know that the selected node was a function which does not work at the bottom of the program tree as it would grow beyond the set bounds, if this logic is defied it jumps to the next one which selects a feature or constant only.
3 - Because a terminal node needs to be either a feature or a constant. A constant is chosen if the random number exceeds the number of features.

Please re-open if you still have questions.
