### ISSUE TITLE
Parrallel and random number

### ISSUE THREAD

**Issue by nasergh** [trevorstephens/gplearn#82]
Hi
i have some experiment with your GP and i see some issue
1- parallel computing is not good enough, because my CPU usage is not going more than 15 % and it's show that parallel part of GP is not good enough, i also try to change number of job but it's make it slower 

2- i did't see any random number in range of const_range=(-1,20) in my result
how GP build random number in formula ? there is probability for this ?

3- it's possible to make function without any input ? i want to give specific number like 1.5 to GP 

4- what fitness function do you suggest for feature selection in 2 class of imbalance dataset?
Thanks

**Comment by trevorstephens** [comment]
1 - parallel will only work well if you have a lot of large programs AND a large population, otherwise the overhead spinning up instances of the evolution will exceed the time it would have taken to just evaluate them.
2 - Random constants are generated at `1/(n+1)` likelihood where n is the number of features in your `X`. If you have a "wide" X with many variables, you will not see many constants.
3 - Please restate this question, I do not understand what you are asking.
4 - `gplearn` currently does not do classification so there is not a solution here. It is slated for the next release but will need a fair bit of work & time to get that completed.

**Comment by nasergh** [comment]
do you have any solution for question 3?( 3- i want to add new function like this
def ret1()
return (2)
as you can see there is no input in this function, how i can define func like this ?)

**Comment by trevorstephens** [comment]
2 - http://gplearn.readthedocs.io/en/stable/intro.html#evolution see reproduction...

3- So just have the function accept the arguments and then do nothing with them within the function...
